services:
  - type: web
    name: facebook-reaction-tool
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fb-react-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.5

databases:
  - name: fb-react-db
    region: ohio
    plan: free